<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>disable</ImplicitUsings>
    <Nullable>disable</Nullable>
    <RootNamespace>WorkerDirectory</RootNamespace>
    <AssemblyName>WorkerDirectory</AssemblyName>
    <InvariantGlobalization>false</InvariantGlobalization>
  </PropertyGroup>

</Project>
